
server:
  port: 8081

spring:
  application:
    name: info

  datasource:
    platform: mysql
    initialization-mode: always
    url: jdbc:mysql://localhost:3306/info?serverTimezone=UTC
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
